- Dockerfile
- requirements.txt
title says it all, please review & merge @sephii
> 1- update debian, python and gdal

- static/css/login.css
- templates/base_generic.html
- templates/registration/login.html
title says it all @sephii please review & merge
> 2- login page layout

- .gitattributes
Time geom - add git attributes to fix line break
> Fix line breaks at git level

- gpf/models.py
- permits/factories.py
- permits/services.py
- permits/templates/permits/emails/permit_request_acknowledgment.txt
- permits/tests.py
- permits/views.py
https://jira.liip.ch/browse/YGDP-22
> YGDP-22 add e-mail notification to permit request author

- geomapshark/settings.py
- permits/templates/geometrywidget/geometrywidget.html
- permits/templates/permits/_permit_request_summary.html
- permits/templates/permits/permit_request_detail.html
- permits/templates/permits/permit_request_geo_time.html
- permits/templatetags/permits_extras.py
> Sprint 5/master ygdp 55

- permits/forms.py
- permits/models.py
- permits/templates/permits/permit_request_detail.html
- permits/templatetags/permits_extras.py
code harmonisation + add status per department for power users.
> Sprint 5/master ygdp 50

- permits/forms.py
Overwrite Django's default behaviour (US date time style).
https://github.com/monim67/django-bootstrap-datepicker-plus/issues/15
> Fix datetime picker

- permits/models.py
- permits/services.py
- permits/tests.py
- permits/views.py
> allow no validation process

- README.md
fix badge in README. Gives the status of the main branch builts.
> Status badge points to main

- permits/templates/permits/_permit_request_summary.html
- permits/templatetags/permits_extras.py
> YC-37 Fix creditor display in request summary

- geomapshark/settings.py
- locale/de/LC_MESSAGES/django.po
- locale/en/LC_MESSAGES/django.po
- locale/it/LC_MESSAGES/django.po
> add german & italian

- .editorconfig
- geomapshark/settings.py
- geomapshark/tests/test_admin_site.py
- geomapshark/tests/test_login.py
- permits/context_processors.py
- permits/forms.py
- permits/management/commands/fixturize.py
- permits/models.py
- permits/services.py
- permits/templates/permits/_permit_progressbar.html
- permits/templates/permits/permit_request_actors.html
- permits/templates/permits/permit_request_appendices.html
- permits/templates/permits/permit_request_geo_time.html
- permits/templates/permits/permit_request_properties.html
- permits/templates/permits/permit_request_select_administrative_entity.html
- permits/templates/permits/permit_request_select_objects.html
- permits/templates/permits/permit_request_select_types.html
- permits/templates/permits/permit_request_submit.html
- permits/templatetags/permits_extras.py
- permits/tests/factories.py
- permits/tests/test_permit_request.py
- permits/tests/test_permit_request_progressbar.py
- permits/tests/utils.py
- permits/utils.py
- permits/views.py
- pyproject.toml
- setup.cfg
By error the previous PR was merged directly on the main branch, so now it needs to be merged on the sprint branch, and probably it would be ok to revert the merge on main
> YC-109 Hide empty steps

- env.demo
- qgisserver/geocity.qgs
- qgisserver/images/print.qgs
Please test (at least for the 2 QGIS files)
> Update ASIT WMTS

- permits/templates/permits/permit_request_detail.html
> display more author info

- permits/filters.py
please review & merge @AlexandreJunod
> filter by permit id

- permits/templates/permits/permit_request_detail.html
> Edit permit_request_detail template

- permits/serializers.py
> add author details to api and remove creditor info from events url

- docker-compose-dev.yml
- docker-compose.yml
- entrypoint_dev.sh
- env.demo
- geomapshark/settings.py
- permits/api.py
- permits/serializers.py
- permits/views.py
- qgisserver/geocity.qgs
> Print production v2

- permits/models.py
> Use term "entité administrative"

- permits/forms.py
Please review.
See https://github.com/yverdon/geocity/pull/244#issuecomment-862280949 for details.
> YC-240 fix: remove field publish

- permits/services.py
- permits/templates/permits/emails/permit_request_validation_reminder.txt
> Uniformize email objects (same verbose level as done in YC-330)

- geomapshark/settings.py
> Remove terms "travaux" and "événement" in title of worktype selection step

- permits/templates/permits/permit_request_detail.html
Following #323 
Please review.
> Fix review of timeline

- permits/templates/permits/permit_request_detail.html
> Fix field name in request template

- permits/admin.py
This reverts commit 0630ea7a0beea7fb00b24a47770ce5c3bb4f17e0.
> Revert "update url for instance server with url suffix"

- permits/templates/permits/_permit_request_summary.html
Span repr (title) element over the whole table and add virtual dd element to keep the rest of the table aligned.
> Span repr (title) element over the whole table

- permits/templates/geometrywidget/geometrywidget.html
First shot, what do you think?
Before
After
> Improve map widget

- permits/serializers.py
@nicolas-sitylb please check & merge :-)
> add bbox to geojson

- templates/base_generic.html
Fix https://jira.liip.ch/browse/YC-562
See each commits for details.
Please review.
> YC-562: Add link to admin panel

- permits/forms.py
- permits/templates/permits/_permit_request_actions.html
Fix https://jira.liip.ch/browse/YC-592
Please review.
> YC-592: Display validation status as radioselect

- permits/tests/test_permit_request_api.py
> Fix API geom tests

- permits/templates/permits/_permit_request_summary.html
- permits/templates/permits/permit_request_detail.html
- static/css/permits.css
Fix https://jira.liip.ch/browse/YC-588
Please review.
> YC-588: Improve permit resumé style

- permits/templates/permits/_permit_request_actions.html
- permits/templates/permits/permit_request_submit.html
Fix https://jira.liip.ch/browse/YC-609
Please review.
> YC-609: Improve backoffice tabs

- permits/templates/permits/permit_request_submit.html
Fix https://jira.liip.ch/browse/YC-625
Please review.
> YC-625: Display directives even with incomplete steps

- permits/tests/test_c_admin_site.py
- templates/base_generic.html
- templates/two_factor/profile.html
> Menu cosmetics

- permits/serializers.py
@nicolas-sitylb Please take a look for the plugin part.
> YC-629: Use actor name in API (instead of its absolute ID)

- static/css/permits.css
Minor, I'll merge after tests.
Before:
After:
> Remove bottom margin for value list properties

- templates/base_generic.html
Fix https://jira.liip.ch/browse/YC-542
> YC-542: Do not display password change in menu for social accounts

- permits/forms.py
- permits/services.py
- permits/tests/test_a_permit_request.py
- permits/views.py
Fix https://jira.liip.ch/browse/YC-604
Please review.
> YC-604: Add type name in email subject

- permits/templates/permits/_permit_request_summary.html
- permits/templates/permits/permit_request_detail.html
- permits/templates/permits/permit_request_submit.html
Fix [YC-757](https://jira.liip.ch/browse/YC-757)
Please review.
After:
Before:
> YC-757: Text for appendices in summary

- permits/tables.py
- permits/templates/permits/permit_request_detail.html
- permits/templates/tables/_permit_request_author_details.html
- permits/templates/tables/_permit_request_author_fullname.html
Fix https://jira.liip.ch/browse/YC-767
Please review.
> YC-767: Do not display author info if anonymous

- geomapshark/settings.py
- permits/templates/permits/permit_request_anonymous_captcha.html
- permits/templates/permits/permit_request_anonymous_sent.html
- permits/templates/permits/permit_request_submit.html
Fix https://jira.liip.ch/browse/YC-766
Please review, see after/before screenshots.
**1**
**2**
**3**
> YC-766: Homogeinize anonymous requests terms

- permits/services.py
> Avoid display of entities that have only anonymous objects

- permits/serializers.py
- permits/services.py
change api variable name and manage the case of inexistant file at the given url in api
> Error of API when file doesn't exist

- permits/templates/permits/permit_request_anonymous_captcha.html
- permits/views.py
Please review.
Tested on envs with and without `PREFIX_URL`.
> YC-659: Fix captcha refresh url

- static/customWidgets/GeometryWidget/geometrywidget.js
Fix https://jira.liip.ch/browse/YC-779
Please review.
> YC-779: Do not add point after map search

- permits/services.py
- permits/templates/permits/emails/permit_request_received_for_services.txt
- permits/tests/test_a_permit_request.py
- permits/views.py
Fix https://jira.liip.ch/browse/YC-734
Please review.
> YC-734: Also notify services when status changes to received

- permits/services.py
Fix https://jira.liip.ch/browse/YC-623
Please review.
> YC-623: Display mandatory contacts first

- geomapshark/tests/test_register.py
- geomapshark/views.py
- templates/registration/emails/email_confirmation.txt
> YC-841: Adapt account validation texts

- templates/base_generic.html
Fix https://jira.liip.ch/browse/YC-837
Please review, see after/before screenshots
> YC-837: Add horizontal padding on mobile devices

- permits/forms.py
Fix https://jira.liip.ch/browse/YC-854
Please review ASAP (its a blocking issue).
> Fix YC-854

- geocity/apps/permits/forms.py
- geocity/apps/permits/templates/permits/emails/permit_request_changed.txt
- geocity/apps/permits/tests/test_a_permit_request.py
Fix https://jira.liip.ch/browse/YC-864
> YC-864: Fix and improve email for permit status changed

- geocity/apps/permits/tables.py
Fix https://jira.liip.ch/browse/YC-863
> YC-863: Add missing verbose name

- geocity/views.py
Minor, I'll merge after tests.
> Adapt text after validation

- geocity/apps/permits/views.py
Minor too, I'll merge after tests.
> Add missing space

- geocity/apps/core/static/js/permit_request_amending.js
Fix https://jira.liip.ch/browse/YC-861
Please review.
> YC-861: Do not allow to send an custom email when status changed to received

- geocity/apps/permits/tables.py
- geocity/apps/permits/templates/tables/_permit_request_author_iban.html
Following https://github.com/yverdon/geocity/pull/542
> YC-836: Add author IBAN (if enabled) in XLS export

- geocity/apps/permits/tables.py
Fix #571 (was not visible only in XLS export...)
Minor, I'll merge after tests are all green.
> Fix IBAN field visibility

- .dockerignore
- .gitignore
- docker-compose.dev.yml
(this contains https://github.com/yverdon/geocity/pull/576 which should be reviewd/merged first)
> YC-806 General refactoring 4 - mount dev volumes under a common folder

- geocity/settings.py
- geocity/urls.py
(this is based on https://github.com/yverdon/geocity/pull/579 which should be reviewed and merged first)
remove unused/incomplete media settings
(they seem unused in the app, and aren't persisted in a volume anyway so data would be lost if they were... the day we need media files, we can readd it)
> YC-806 General refactoring 6 - remove unused/incomplete media settings

- geocity/apps/permits/admin.py
Fix https://jira.liip.ch/browse/YC-874
> YC-874: Add WOT in 1.5 and 2.2 admin

- geocity/apps/permits/templates/permits/_field_value_list.html
> YC-610 (fix): Do not use new lines in list template since <br> are rendered

- geocity/apps/permits/forms.py
Fix regression introduced in #584, related to https://jira.liip.ch/browse/YC-907
> YC-907 (fix): Use default WOT name if shortname is not defined

- geocity/apps/submissions/tables.py
- geocity/apps/submissions/templates/tables/_submission_author_details.html
- geocity/apps/submissions/templates/tables/_submission_author_fullname.html
- geocity/apps/submissions/templates/tables/_submission_author_iban.html
> Fix author in templates

- geocity/apps/api/serializers.py
Rename field_values into fields_values for /rest/submissions_details/ route in API
> phoenix-api

- geocity/apps/accounts/templates/registration/login.html
- geocity/apps/accounts/templates/two_factor/login.html
- geocity/apps/core/static/css/login.css
- geocity/apps/submissions/templates/submissions/submission_appendices.html
Following #624
- Remove homepage top links since they are now in the footer
- Fix the size of the links
- Fix footer in appendices step
- Fix reset link which was hidden by footer on small height screen
Please review.
> YC-943: Improve footer links

- geocity/apps/accounts/templates/two_factor/profile.html
- geocity/apps/accounts/urls.py
- geocity/apps/accounts/views.py
Needs to be refactored for a DRYer solution
> YC-869: Keep url filters after login on 2FA instance

- geocity/apps/submissions/templates/submissions/widgets/multipleselect.html
> Improve visual rendering of category cards

- geocity/apps/accounts/views.py
- geocity/apps/core/templates/base_generic.html
- geocity/settings.py
Fix https://jira.liip.ch/browse/YC-15
> YC-15: Update footer

- geocity/apps/submissions/templates/submissions/_submission_actions.html
Fix https://jira.liip.ch/browse/YC-975
> YC-975: Allow HTML in additional_information also in backoffice

- geocity/apps/submissions/templates/submissions/submission_submit.html
Fix https://jira.liip.ch/browse/YC-976
> YC-976: Duplicate the submit button after the resume and put the incomplete button after the incomplete text

- .env.example
- geocity/apps/accounts/dootix/provider.py
- geocity/apps/accounts/geomapfish/provider.py
- geocity/apps/accounts/models.py
- geocity/apps/api/views.py
- geocity/apps/permits/fields.py
- geocity/apps/reports/models.py
- geocity/apps/submissions/exceptions.py
- geocity/apps/submissions/fields.py
- geocity/apps/submissions/forms.py
- geocity/apps/submissions/models.py
- geocity/apps/submissions/services.py
- geocity/apps/submissions/shortcuts.py
- geocity/apps/submissions/views.py
- geocity/tests/reports/test_reports.py
Something that was forgotten during phoenix.
> Remove old refs to permit-request in comments/logs

- geocity/apps/submissions/cron.py
- geocity/apps/submissions/fields.py
- geocity/apps/submissions/forms.py
- geocity/apps/submissions/models.py
- geocity/apps/submissions/services.py
- geocity/apps/submissions/templates/submissions/emails/submission_acknowledgment.txt
- geocity/apps/submissions/templates/submissions/emails/submission_changed.txt
- geocity/apps/submissions/templates/submissions/emails/submission_classified.txt
- geocity/apps/submissions/templates/submissions/emails/submission_classified_for_services.txt
- geocity/apps/submissions/templates/submissions/emails/submission_complemented.txt
- geocity/apps/submissions/templates/submissions/emails/submission_inquiry_closing.txt
- geocity/apps/submissions/templates/submissions/emails/submission_prolongation.txt
- geocity/apps/submissions/templates/submissions/emails/submission_prolongation_for_services.txt
- geocity/apps/submissions/templates/submissions/emails/submission_prolongation_reminder.txt
- geocity/apps/submissions/templates/submissions/emails/submission_received.txt
- geocity/apps/submissions/templates/submissions/emails/submission_received_for_services.txt
- geocity/apps/submissions/templates/submissions/emails/submission_submitted.txt
- geocity/apps/submissions/templates/submissions/emails/submission_submitted_with_mention.txt
- geocity/apps/submissions/templates/submissions/emails/submission_validated.txt
- geocity/apps/submissions/templates/submissions/emails/submission_validation_reminder.txt
- geocity/apps/submissions/templates/submissions/emails/submission_validation_request.txt
- geocity/apps/submissions/views.py
- geocity/tests/submissions/functional/test_submission_amendment.py
- geocity/tests/submissions/functional/test_submission_classify.py
- geocity/tests/submissions/functional/test_submission_validation.py
- geocity/tests/submissions/test_a_permit_request.py
Fix https://jira.liip.ch/browse/YC-1009
> YC-1009: Put form names in email subject

- geocity/apps/submissions/services.py
- geocity/apps/submissions/templates/submissions/emails/submission_acknowledgment.txt
- geocity/apps/submissions/templates/submissions/emails/submission_refund.txt
Fix https://jira.liip.ch/browse/YC-1014
> YC-1014: Uniformize payment emails with other ones

- geocity/apps/submissions/templates/submissions/_submission_summary.html
- geocity/apps/submissions/templatetags/submissions_extras.py
- geocity/apps/submissions/views.py
- geocity/tests/submissions/functional/test_complementary_documents.py
Fix https://jira.liip.ch/browse/YC-1012
> YC-1012: Do not allow submission author to delete documents

- geocity/apps/core/static/css/main.css
- geocity/apps/reports/management/commands/add_payment_reports.py
- geocity/apps/submissions/templates/submissions/_submission_actions.html
Fix https://jira.liip.ch/browse/YC-1021
> YC-1021: Minor improvements for payment

- geocity/apps/submissions/management/commands/fixturize.py
Fix https://jira.liip.ch/browse/YC-1028
> YC-1028: Fix demo phone numbers

- geocity/apps/core/static/css/main.css
- geocity/apps/submissions/templates/submissions/_directives_and_legal_cta.html
- geocity/apps/submissions/templates/submissions/submission_appendices.html
- geocity/apps/submissions/templates/submissions/submission_contacts.html
- geocity/apps/submissions/templates/submissions/submission_geo_time.html
Following https://github.com/yverdon/geocity/pull/671
Main change on contacts step.
After:
Before:
> YC-988: Improve the placement of the directives and legal CTA

- geocity/apps/core/static/js/submissions_submit.js
- geocity/apps/submissions/templates/submissions/submission_detail.html
- geocity/apps/submissions/templates/submissions/submission_submit.html
Fix https://jira.liip.ch/browse/YC-1030
> YC-1030-2: Remove number of first geotime form

- geocity/apps/submissions/templates/submissions/widgets/categorized_groupedradio.html
Fix https://jira.liip.ch/browse/YC-1038
After:
Before:
> YC-1038-2: Fix style for unique form selection

- geocity/apps/submissions/forms.py
- geocity/apps/submissions/services.py
- geocity/apps/submissions/templates/submissions/emails/submission_acknowledgment.txt
- geocity/apps/submissions/templates/submissions/emails/submission_changed.txt
- geocity/apps/submissions/templates/submissions/emails/submission_received.txt
- geocity/apps/submissions/templates/submissions/emails/submission_received_for_services.txt
- geocity/apps/submissions/templates/submissions/emails/submission_submitted.txt
- geocity/apps/submissions/templates/submissions/emails/submission_submitted_with_mention.txt
- geocity/apps/submissions/views.py
- geocity/tests/submissions/functional/test_submission_amendment.py
- geocity/tests/submissions/test_a_permit_request.py
Fix https://jira.liip.ch/browse/YC-1039
> YC-1039-2: Use term demande/annonce for some emails

- geocity/apps/submissions/templates/submissions/_directives_and_legal.html
Fix https://jira.liip.ch/browse/YC-1066
> YC-1066: Rename link download directive to download document

- geocity/apps/submissions/templates/submissions/_submission_summary.html
Fix https://github.com/yverdon/geocity/commit/4a9cf5af6910e371908b7b4b08137e1e3ca7b5fe
> Fix title fix

- geocity/apps/accounts/admin.py
Add more information on group page of the django admin.
- Show number of forms associated to an integrator
- Show number of sites associated to an integrator
> Show number of forms and sites associated to an integrator

- geocity/apps/submissions/templates/submissions/_submission_summary.html
Fix https://jira.liip.ch/browse/YC-1081
After:
Before:
> YC-1081: Fix contact indentation in summary

- geocity/apps/accounts/models.py
- geocity/apps/forms/models.py
- geocity/apps/submissions/forms.py
Fix https://jira.liip.ch/browse/YC-1084
> YC-1084: Sort alphabetically entities with same ofs_id

- geocity/apps/submissions/templates/submissions/_submission_actions.html
- geocity/apps/submissions/views.py
...and vice-versa
Fix https://jira.liip.ch/browse/YC-916
> YC-916: Add buttons to stay on submission page for pilots with validator permission

- geocity/apps/forms/admin.py
Fix https://jira.liip.ch/browse/YC-1079
> YC-1079: Filter reports in paymentsettings admin

- geocity/apps/submissions/tables.py
- geocity/apps/submissions/templates/tables/_submission_selected_price.html
- geocity/tests/submissions/unit/test_submission.py
Fix https://jira.liip.ch/browse/YC-1092
> YC-1092: Add selected price to dashboard and excel export

- geocity/apps/accounts/templates/accounts/user_profile_edit.html
- geocity/apps/submissions/templates/submissions/submission_submit.html
Fix https://jira.liip.ch/browse/YC-1094
> YC-1094: Add general condition acceptance in create profile form

- geocity/apps/submissions/forms.py
- geocity/apps/submissions/views.py
Only people with `has_permission_to_edit_submission_validations` set to True can change visiblity status
> YC-1095: Disable field if user is only validator

- geocity/apps/submissions/search.py
Fix https://jira.liip.ch/browse/YC-1099
> YC-1099: Strip search string

- geocity/apps/submissions/tables.py
- geocity/apps/submissions/templates/tables/_submission_forms_str.html
Fix https://jira.liip.ch/browse/YC-1044
> YC-1044: Fix missing form names in XLS export

- geocity/apps/submissions/templates/tables/_submission_status.html
Fix https://jira.liip.ch/browse/YC-1098
> YC-1098: Use more generic term when submissions need to be classified

- geocity/apps/submissions/views.py
Fix https://jira.liip.ch/browse/YC-1087
> YC-1087: Do not allow price edit if form was submitted

- geocity/apps/submissions/forms.py
Fix https://jira.liip.ch/browse/YC-917
> YC-917: Add missing required class in classify form

- geocity/apps/forms/admin.py
- geocity/apps/forms/models.py
Fix https://jira.liip.ch/browse/YC-1102
> YC-1102: Display nb of submissions taken into account if a maximum limit is defined

- geocity/apps/submissions/models.py
- geocity/apps/submissions/templates/submissions/_submission_actions.html
Fix https://jira.liip.ch/browse/YC-661
> YC-661: Hide some panels if submission is approved or rejected

- geocity/apps/accounts/templates/account/lockout.html
- geocity/apps/accounts/views.py
- geocity/apps/core/templates/base_generic.html
- geocity/settings.py
Fix https://jira.liip.ch/browse/YC-1109
> YC-1109: Add optional link to legal notice

- geocity/apps/accounts/templates/account/lockout.html
- geocity/apps/core/templates/base_generic.html
- geocity/settings.py
Fix https://jira.liip.ch/browse/YC-1110
> YC-1110: Add a tooltip to abbreviated footer links

- geocity/apps/forms/models.py
Bad commit: https://github.com/yverdon/geocity/commit/8335aa80a88531c88236b948260afc8f10ef02da
> Fix release conflict

- geocity/apps/reports/models.py
- geocity/apps/submissions/forms.py
- geocity/apps/submissions/models.py
https://jira.liip.ch/browse/YC-1111
> yc-1111 change mail redirection on awaiting supplement

- geocity/apps/accounts/permissions_groups.py
Fix https://jira.liip.ch/browse/YC-1118
> YC-1118: Remove no more used default permission

- geocity/apps/submissions/filters.py
- geocity/apps/submissions/views.py
> Show drafts first

- geocity/apps/submissions/templatetags/submissions_extras.py
Fix https://jira.liip.ch/browse/YC-1124
> YC-1124: Render date field correctly

- geocity/apps/reports/models.py
Fix https://jira.liip.ch/browse/YC-1135
> YC-1135: Add a custom filter to format API date in jinja print output

- geocity/apps/submissions/models.py
Fix https://jira.liip.ch/browse/YC-1139
> YC-1139: Get submission_id instead of submission_id index

- geocity/apps/forms/admin.py
Fix https://jira.liip.ch/browse/YC-1151
> YC-1151: Display forms related to the current field

- geocity/apps/accounts/admin.py
- geocity/apps/accounts/users.py
- geocity/apps/forms/admin.py
- geocity/apps/forms/models.py
- geocity/apps/submissions/steps.py
- geocity/apps/submissions/views.py
- geocity/tests/factories.py
adapt quick_access_slug to work with anonymous forms, prevent from accessing anonymous forms without being anonymous user
> Anonymous issues and features

- geocity/apps/core/static/js/submission_contacts.js
- geocity/apps/submissions/forms.py
Fix https://jira.liip.ch/browse/YC-1152
> YC-1152: Fix some contact bugs

- docker-compose.dev.yml
- docker-compose.yml
- geocity/apps/submissions/templates/advancedgeometrywidget/geometrywidget.html
- geocity/settings.py
- services/external_statics/Dockerfile
Configure external statics
[] Check that collectstatics is OK and that statics files are served correctly with whitenoise
> Include agenda statics

- geocity/apps/api/views.py
Not tested @AlexandreJunod , please check
> add fts search - wip

- geocity/apps/submissions/forms.py
Fix https://jira.liip.ch/browse/YC-1158
> YC-1158: Select the only available price by default

- geocity/apps/submissions/tables.py
Fix https://jira.liip.ch/browse/YC-1167
> YC-1167: Fix null selected form in full XLS export

- .env.example
- docker-compose.yml
- entrypoint.sh
Fix https://jira.liip.ch/browse/YC-1170
> YC-1170: Add a new env variable to disable migration script at prod startup

- geocity/apps/accounts/templates/registration/emails/email_confirmation.txt
- geocity/apps/accounts/templates/registration/emails/email_enumeration_attack_evaded.txt
- geocity/apps/accounts/templates/registration/password_reset_email.html
- geocity/apps/submissions/templates/submissions/emails/submission_classified_for_services.txt
- geocity/apps/submissions/templates/submissions/emails/submission_complemented.txt
- geocity/apps/submissions/templates/submissions/emails/submission_prolongation_for_services.txt
- geocity/apps/submissions/templates/submissions/emails/submission_received_for_services.txt
- geocity/apps/submissions/templates/submissions/emails/submission_submitted.txt
- geocity/apps/submissions/templates/submissions/emails/submission_submitted_with_mention.txt
- geocity/apps/submissions/templates/submissions/emails/submission_validated.txt
- geocity/apps/submissions/templates/submissions/emails/submission_validation_reminder.txt
- geocity/apps/submissions/templates/submissions/emails/submission_validation_request.txt
Fix https://jira.liip.ch/browse/YC-1162
> YC-1162: Add user name in all emails

- geocity/apps/submissions/forms.py
Fix https://jira.liip.ch/browse/YC-1175
> YC-1175: Display helptext for file fields

- geocity/apps/core/static/js/submission_submit.js
Fix https://jira.liip.ch/browse/YC-1176
> YC-1176: Hide geotime number if unique

- geocity/apps/submissions/templates/submissions/submission_detail.html
Fix https://jira.liip.ch/browse/YC-1177
> YC-1177: Display user full name in timeline instead of username

- geocity/apps/submissions/templates/submissions/submission_detail.html
Fix https://jira.liip.ch/browse/YC-1180
After:
Before:
> YC-1180: Do not display inexistant infos of deleted users

- geocity/apps/submissions/views.py
Prevent a validator with pilot group for other entity, to archive requests where he isn't pilot
> Fix archive permissions

- services/pdf/requirements.txt
> Revert "Bump idna from 3.6 to 3.7 in /services/pdf"

- geocity/apps/submissions/templates/submissions/_submission_actions.html
- geocity/apps/submissions/views.py
don't show classify / poke step if not availabled in administrative entity statuses
> Hide classify/poke step if not available in entity statuses

- geocity/apps/submissions/views.py
Fix https://jira.liip.ch/browse/YC-1189
> YC-1189: Generate transaction PDF only if transaction is authorized

- geocity/apps/submissions/services.py
- geocity/tests/submissions/test_a_permit_request.py
Fix https://jira.liip.ch/browse/YC-598
> YC-598: Handle special chars in email sender name

- geocity/apps/reports/management/commands/add_payment_reports.py
Apply https://github.com/yverdon/geocity/commit/954f4ff010f73b4b4471b9b5efe830d7c8442709 to payment reports creation script
> Apply CKEditor migration to payment reports

- geocity/apps/reports/templates/reports/sections/sectionamendproperty.html
- geocity/apps/reports/templates/reports/sections/sectiondetail.html
- geocity/apps/reports/views.py
- Interpret line breaks for validation and amend_fields
- Interpret line breaks on fields for details model
- Add new field.value_formatted to remove brackets from lists
- Support api_name on undesired fields on section detail [YC-1128](https://jira.liip.ch/browse/YC-1128)
- Replace True/False by Vrai/Faux for boolean fields
> [RM-1] interpret end of line for validation and amend_fields comments

- geocity/tests/submissions/functional/test_submission_validation.py
To avoid regression https://github.com/yverdon/geocity/pull/1019
> YC-1146: Add UI test when validation by validators is disabled
