- Dockerfile
- docker-compose-dev.yml
- entrypoint.sh
- geomapshark/settings.py
- requirements.in
- requirements.txt
@sephii , @nicolas-sitylb 
- Change base docker image to official osge/gdal/ubuntu image (gdal 3.1.0, ubuntu 20). Using small image
- Add missing lib to image: gettext, cairo, pango, ...
- Add missing dependencies to python: tablib + pycairo
@sephii please merge. Tested on both windows & ubuntu
> Dockerfile

- geomapshark/settings.py
- permits/api.py
This PR add check for remote host ip for accessing permits endpoints. White list is defined in constance variable
In order not to block docker private ip in dev mode, private ip are whitelisted by default. But this can change in production through constance variable ENDPOINT_WHITELIST
@AlexandreJunod please review & merge
> whitelist ip for endpoints

- templates/base_generic.html
Using the default value `strict-origin-when-cross-origin` allows to access external WMS layers with referrer check.
Doc: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy
Please review.
> Allow to access external WMS layers with referrer check

- Dockerfile
- django_wfs3/README.md
- django_wfs3/mixins.py
- django_wfs3/pagination.py
- django_wfs3/routers.py
- django_wfs3/urls.py
- django_wfs3/views.py
- geomapshark/settings.py
- geomapshark/urls.py
- permits/api.py
- permits/geoservices.py
- permits/serializers.py
- permits/urls.py
- requirements.in
- requirements.txt
- requirements_dev.txt
This is the WIP implementation for WFS3 (aka OGC Features API) for Django applied to Geocity.
Please see `django_wfs3/README.md` for more info on implementation.
It's not ready yet, but opening this PR already so you can review and see if it takes the desired direction.
Roadmap :
> [DRAFT] OGC Features API (wfs3) endpoint

- permits/api.py
@monodo Tell me what do you think. Here is the result:
In an ideal world, il would also rename the `geom_type_name` displayed in title and abstract, but since the keywords are also used as query parameters `geom_type`, it would be confusing to have 2 spellings (and I don't want to break the API).
See each commits for detailed information on changes.
> Fix WFS3 description

- docker-compose-demo.yml
- docker-compose-dev.yml
Migrates to PG13 in both the development and the demo Compose files.
You will probably have to `down -v` if you have a previous version of a PG database running in order to set it up with the newest version.
> Migrate to PG13.

- permits/models.py
Fix https://jira.liip.ch/browse/YC-225
Since the value is also displayed in the resumé, I didn't used the `>` but `:` (`>` was good only for navigation purpose).
Should we display it `foo: bar` or `foo : bar`?
Please review.
> YC-225: Change order of WorksObjectType string value

- permits/forms.py
- permits/services.py
- permits/templates/permits/_permit_request_actions.html
- permits/tests/test_a_permit_request.py
- permits/views.py
Fix https://jira.liip.ch/browse/YC-563
Please review and test.
For a reason I don't get, there is no change detected after editing the helper_text:
```
python manage.py makemigrations -n fix_typo
No changes detected
```
> YC-563: Display prolongation tab only if request can be prolonged

- permits/templates/permits/_permit_request_actions.html
Fix something that was never working... (when only `additional_information` is set)
I used the same logical as in https://github.com/yverdon/geocity/blob/main/permits/templates/permits/permit_request_submit.html#L28-L40
> Fix never displaying directive addtionnal info

- permits/models.py
- permits/search.py
Fix https://jira.liip.ch/browse/YC-607
Please review.
For now, the rendering of multiple list is like that:
I don't know if we can improve this rendering without breaking the resumé layout.
> Add some other field types in search

- requirements.txt
- requirements_dev.txt
Related to #415 
Social login was broken...
Perhaps something related to:
- https://django-allauth.readthedocs.io/en/latest/release-notes.html#backwards-incompatible-changes-2
- https://django-allauth.readthedocs.io/en/latest/release-notes.html#backwards-incompatible-changes-1
> Revert django-allauth update

- static/css/permits.css
Fix https://jira.liip.ch/browse/YC-599
Please review.
Before:
After:
> YC-599: Fix display of `*` for mandatory checkboxes

- requirements.in
- requirements.txt
- requirements_dev.txt
Fix https://jira.liip.ch/browse/YC-858
Stick allauth to specific version, same as done in #416, to make social login working...
> YC-858: Use allauth specific version

- geocity/apps/permits/forms.py
Fix https://jira.liip.ch/browse/YC-865
> YC-865: Do not add approved and rejected statuses for permit with backoffice field always updatable

- .github/workflows/main.yml
- geocity/apps/reports/tests/base.py
Adds some very small tolerance to report rendering tests.
Also includes a follow up to the main refactoring which broke uploading the tests artifacts to the CI pipeline
> YC-882 fix flaky report rendering tests

- geocity/apps/permits/templates/permits/_permit_request_summary.html
- geocity/apps/permits/templates/permits/permit_request_detail.html
Fix https://jira.liip.ch/browse/YC-610
After:
Before:
> YC-610: Render line breaks for multiline text fields

- geocity/apps/permits/cron.py
- geocity/apps/permits/forms.py
- geocity/apps/permits/models.py
- geocity/apps/permits/services.py
- geocity/apps/permits/templates/permits/emails/permit_request_acknowledgment.txt
- geocity/apps/permits/templates/permits/emails/permit_request_changed.txt
- geocity/apps/permits/templates/permits/emails/permit_request_classified.txt
- geocity/apps/permits/templates/permits/emails/permit_request_classified_for_services.txt
- geocity/apps/permits/templates/permits/emails/permit_request_complemented.txt
- geocity/apps/permits/templates/permits/emails/permit_request_inquiry_closing.txt
- geocity/apps/permits/templates/permits/emails/permit_request_prolongation.txt
- geocity/apps/permits/templates/permits/emails/permit_request_prolongation_for_services.txt
- geocity/apps/permits/templates/permits/emails/permit_request_prolongation_reminder.txt
- geocity/apps/permits/templates/permits/emails/permit_request_received.txt
- geocity/apps/permits/templates/permits/emails/permit_request_received_for_services.txt
- geocity/apps/permits/templates/permits/emails/permit_request_submitted.txt
- geocity/apps/permits/templates/permits/emails/permit_request_submitted_with_mention.txt
- geocity/apps/permits/templates/permits/emails/permit_request_validated.txt
- geocity/apps/permits/templates/permits/emails/permit_request_validation_reminder.txt
- geocity/apps/permits/templates/permits/emails/permit_request_validation_request.txt
- geocity/apps/permits/tests/test_a_permit_request.py
- geocity/apps/permits/views.py
Fix https://jira.liip.ch/browse/YC-883
I also added the types list in mail subject https://github.com/yverdon/geocity/pull/408 where it was missing.
> YC-883: Add objects list in emails

- geocity/apps/accounts/views.py
Following https://github.com/yverdon/geocity/pull/670
Tested on my prod (where `siteprofile__site_id` <> `siteprofile__id`)
> YC-1019 (fix): Fix filter to get the right site_custom_template

- geocity/apps/forms/admin.py
- geocity/apps/reports/admin.py
- geocity/apps/reports/templates/reports/sections/sectiondetail.html
Make admin more easy to configure by adding more visibility of elements using : 
- get_list_display
- get_search_fields
- get_list_filter
- Custom data (like [this](https://github.com/yverdon/geocity/pull/750/files#diff-ab1253e47db5cfdade10f9bceb6b5a218f3b7d451c18810bf091e228c8fb467aL151))
Superuser and integrator should have a different view. Show usefull data to make it easier to retrieve elements
> Improve admin interface 

- geocity/apps/submissions/templates/submissions/emails/submission_classified.txt
- geocity/apps/submissions/templates/submissions/submission_geo_time.html
Not sure if it's also recommended to rename [here](https://github.com/yverdon/geocity/blob/main/geocity/apps/submissions/shortcuts.py#L14) (since `submission` is already set)?
> Rename forgotten permit_request variables

- geocity/apps/core/static/css/main.css
> Display the text of select at the same place as before

- geocity/apps/core/static/css/main.css
Currently the color is too close to the status accepted
After:
Before:
> Use a better color for status processing

- entrypoint.sh
- geocity/apps/accounts/management/commands/update_integrator_permissions.py
⚠️ If migrations are not run, `update_integrator_permissions` must also be run automatically
> run collect static in anycase

- geocity/apps/forms/admin.py
1. Remove `max_submissions_message` because the default value is rather long and messes up the table layout
2. Display `validation_document_required_for` only if `validation_document` is set
> Improve form admin fields display

- geocity/apps/forms/models.py
When an integrator is also in a pilot group, he should see both administrative entites he created but also thoses associated to other groups he's in.
> add entities the integrator is in from other groups

- geocity/apps/submissions/templates/submissions/emails/submission_classified_for_services.txt
- geocity/apps/submissions/templates/submissions/emails/submission_complemented.txt
- geocity/apps/submissions/templates/submissions/emails/submission_prolongation_for_services.txt
- geocity/apps/submissions/templates/submissions/emails/submission_received_for_services.txt
- geocity/apps/submissions/templates/submissions/emails/submission_submitted.txt
- geocity/apps/submissions/templates/submissions/emails/submission_submitted_with_mention.txt
- geocity/apps/submissions/templates/submissions/emails/submission_validated.txt
- geocity/apps/submissions/templates/submissions/emails/submission_validation_reminder.txt
- geocity/apps/submissions/templates/submissions/emails/submission_validation_request.txt
Wrong implementation in https://github.com/yverdon/geocity/pull/936
> Remove author name falsely used as recipient name in backoffice emails

- .env.example
- docker-compose.yml
- geocity/settings.py
https://docs.djangoproject.com/en/5.0/ref/settings/#csrf-trusted-origins
> allow configuration in .env

- geocity/apps/submissions/models.py
Quick implementation of an additional backend check for cases where the browser do not recognize the additional extension restrictions.
TODOs @AlexandreJunod :
> backend check for additional file extension restrictions

- geocity/apps/submissions/templates/submissions/_submission_actions.html
The condition added in https://github.com/yverdon/geocity/pull/910/files#diff-a9ad40719e1ddddf96d55340a7a38e6694d31375c596ed440823f71dbdc26bc0 was removed (unintentionally?) in https://github.com/yverdon/geocity/commit/6f2103402be4a307cf7d2ede970cb823a0a4e71a#diff-a9ad40719e1ddddf96d55340a7a38e6694d31375c596ed440823f71dbdc26bc0R21 in https://github.com/yverdon/geocity/pull/925, so the possibility to skip validation by validators step wasn't working anymore...
This PR fixes that.
> YC-1146 (revival): Re add possibility to skip validation by validators step
